owi535:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 30
  
  # Position Controllers ---------------------------------------
  rotationbase_position_controller:
    type: effort_controllers/JointPositionController
    joint: rotationbase
    pid: {p: 100.0, i: 0.01, d: 10.0}
  shoulder_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder
    pid: {p: 100.0, i: 0.01, d: 10.0}
  elbow_position_controller:
    type: effort_controllers/JointPositionController
    joint: elbow
    pid: {p: 100.0, i: 0.01, d: 10.0}
  wrist_position_controller:
    type: effort_controllers/JointPositionController
    joint: wrist
    pid: {p: 100.0, i: 0.01, d: 10.0}
  gripper_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_grip
    pid: {p: 100.0, i: 0.01, d: 10.0}
